news: Add release post for 0.17.1
xmonad/xmonad-web pull request #67
Opened 2022-08-29 16:46 UTC by slotThe

To get this party started, let us start with a _very rough_ first draft of a release post!  Hopefully inspiration strikes sometime this week.

2022-08-29 17:44 UTC, TheMC47 commented on news/_posts/2022-09-03-xmonad-0-17-1.md
> +## xmonad-contrib 0.17.0
This should be 0.17.1, right?

2022-08-29 18:12 UTC, eyenx requested changes

2022-08-29 18:12 UTC, eyenx commented on news/_posts/2022-09-03-xmonad-0-17-1.md
> +## xmonad-contrib 0.17.0
```suggestion
## xmonad-contrib 0.17.1
```

2022-08-29 18:22 UTC, slotThe commented on news/_posts/2022-09-03-xmonad-0-17-1.md
> +## xmonad-contrib 0.17.0
indeed!

2022-09-02 05:54 UTC, psibi commented
@slotThe What do you think about doing a release of xmonad-extras-0.17.1 also along with it ? There is one module which has been added to it: https://github.com/xmonad/xmonad-extras/pull/32

2022-09-02 07:03 UTC, slotThe commented
@psibi yeah that sounds good to me!

2022-09-03 13:28 UTC, geekosaur approved these changes
Aside from that, it looks okay

2022-09-03 13:28 UTC, geekosaur commented on news/_posts/2022-09-03-xmonad-0-17-1.md
> +  + `behaviourMonad.Util.DynamicScratchpads`: deprecated the module; use
Did `behaviour` belong somewhere else?

2022-09-03 13:34 UTC, slotThe commented on news/_posts/2022-09-03-xmonad-0-17-1.md
> +  + `behaviourMonad.Util.DynamicScratchpads`: deprecated the module; use
hah, indeed :)

2022-09-03 14:01 UTC, merged